.TH PHYTA 6 "March 2016"
.SH NAME
phyta \- strange and a bit surrealistic game
.SH SYNOPSIS
.B phyta
.SH OPTIONS
This game has no command line options.
.SH FILES
BlitzMax source code: /usr/share/doc/phyta/White.bmx.gz
.SH SEE ALSO
.I http://www.cambriangames.com/current
.SH AUTHOR
Copyright \(co 2008 Abraham Parangi <\fIabraham.parangi@gmail.com\fR>
