#!/bin/sh

data="/usr/share/games/SSVOpenHexagon"
conf="$HOME/.config/OpenHexagon"
ohdir="/usr/lib/SSVOpenHexagon"

if [ ! -d "$conf" ]; then
  mkdir -p "$conf"
  cp -r $data/Assets "$conf"
  cp -r $data/ConfigOverrides "$conf"
  cp -r $data/Packs "$conf"
  cp -r $data/Profiles "$conf"
  cp -r $data/config.json "$conf"
fi

test -e "$HOME/OpenHexagon" || ln -s "$conf" "$HOME/OpenHexagon"

systemlibs="/lib/x86_64-linux-gnu:/lib:/usr/lib/x86_64-linux-gnu:/usr/lib:/usr/local/lib"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$ohdir/libs1:$systemlibs:$ohdir/libs2"
cd "$conf" && "$ohdir/SSVOpenHexagon" $*
