.\" 
.TH "the question" "6" "May 2008" "" "Games"
.SH "NAME"
the_question \- a simple visual\-novel game with the Ren'Py engine
.SH "SYNOPSIS"
.B the_question
.SH "DESCRIPTION"
This is a very simple Visual Novel game.
.SH "SEE ALSO"
The source code for the demo script is at /usr/share/games/renpy/the_question/

You can find more information at http://www.renpy.org/
