include ../../mk/include.mk

deps   = git
srcpkg = hybrid-avisynth-extension

download:
	rm -rf $(builddir)
	git clone --depth 1 --branch avisynth-extension "https://github.com/darealshinji/hybrid-debian.git" $(builddir)

