#!/bin/sh

dirname="/usr/lib/xnviewmp"
path1="$dirname/lib:$dirname/Plugins:$LD_LIBRARY_PATH"
path2="$dirname/lib:$QT_PLUGIN_PATH"

if [ $# -lt 1 ]; then
  LD_LIBRARY_PATH="$path1" QT_PLUGIN_PATH="$path2" "$dirname/XnView"
else
  LD_LIBRARY_PATH="$path1" QT_PLUGIN_PATH="$path2" "$dirname/XnView" "$@"
fi
