.TH NEROAACDEC 1 "MAY 2014" "1.5.1.0"
.SH NAME
neroAacDec \- Nero AAC Decoder
.SH SYNOPSIS
.B neroAacDec -if \fR<input-file> \fB-of \fR<output-file> \fB[-chapter \fR<number\fR>\fB]
.br
.B neroaacdec

.SH DESCRIPTION
Package build date: Dec 17 2009
.br
Package version:    1.5.1.0
.PP
Specify - to decode to stdout

.SH SEE ALSO
/usr/share/doc/neroaac/
.br
.I http://www.nero.com/eng/company/about-nero/nero-aac-codec.php
.SH COPYRIGHT
Copyright \(co 2006-2010 Nero AG. All Rights Reserved Worldwide.
