include ../../mk/include.mk

deps     = wget
builddir = telxcc-2.5.3

download:
	@ $(call download,telxcc.tar.gz,https://github.com/petrkutalek/telxcc/archive/v2.5.3.tar.gz)
	tar xvf telxcc.tar.gz
	rm $(builddir)/Makefile

