#!/bin/sh

# I, djcj <djcj@gmx.de>, hereby release this code to the Public Domain.
# No license required for any purpose; the work is not subject to copyright in any jurisdiction.

set -e

verifysha256 () {
	sha256_2=$(sha256sum ${1} | head -c64)
	if [ $sha256_2 != ${2} ] ; then
		echo "${1}:"
		echo "SHA256 checksum is $sha256_2 but should be ${2}."
		echo "Delete '${1}' and try it again."
		exit 1
	else
		echo "${1}: checksum ok."
	fi
}

gcc_ver=5.4.0
gcc_dir=gcc-$gcc_ver
gcc_pkg=${gcc_dir}.tbz
gcc_url="http://ftp.gnu.org/gnu/gcc/gcc-$gcc_ver/${gcc_dir}.tar.bz2"
gcc_sum=608df76dec2d34de6558249d8af4cbee21eceddbcb580d666f7a5a583ca3303a

binutils_ver=2.28
binutils_dir=binutils-$binutils_ver
binutils_pkg=${binutils_dir}.tbz
binutils_url="https://ftp.gnu.org/gnu/binutils/${binutils_dir}.tar.bz2"
binutils_sum=6297433ee120b11b4b0a1c8f3512d7d73501753142ab9e2daa13c5a3edd32a72

mpfr_dir=mpfr-3.1.5
mpc_dir=mpc-1.0.3
gmp_dir=gmp-6.1.2
isl_dir=isl-0.17.1

mpfr_pkg=${mpfr_dir}.txz
mpc_pkg=${mpc_dir}.tgz
gmp_pkg=${gmp_dir}.txz
isl_pkg=${isl_dir}.txz

mpfr_url="http://www.mpfr.org/${mpfr_dir}/${mpfr_dir}.tar.xz"
mpc_url="https://ftp.gnu.org/gnu/mpc/${mpc_dir}.tar.gz"
gmp_url="https://gmplib.org/download/gmp/${gmp_dir}.tar.xz"
isl_url="http://isl.gforge.inria.fr/${isl_dir}.tar.xz"

mpfr_sum=015fde82b3979fbe5f83501986d328331ba8ddf008c1ff3da3c238f49ca062bc
mpc_sum=617decc6ea09889fb08ede330917a00b16809b8db88c29c31bfbb49cbf88ecc3
gmp_sum=87b565e89a9a684fe4ebeeddb8399dce2599f9c9049854ca8c0dfbdea0e21912
isl_sum=be152e5c816b477594f4c6194b5666d8129f3a27702756ae9ff60346a8731647

test -f $gcc_pkg || wget -O $gcc_pkg $gcc_url
test -f $binutils_pkg || wget -O $binutils_pkg $binutils_url
test -f $mpfr_pkg || wget -O $mpfr_pkg $mpfr_url
test -f $mpc_pkg || wget -O $mpc_pkg $mpc_url
test -f $gmp_pkg || wget -O $gmp_pkg $gmp_url
test -f $isl_pkg || wget -O $isl_pkg $isl_url

if [ "x$1" = "x--extract" ]; then
	set -v
	tar xf $binutils_pkg && mv $binutils_dir binutils-src
	tar xf $gcc_pkg && mv $gcc_dir gcc-src
	tar xf $mpfr_pkg && mv $mpfr_dir mpfr
	tar xf $mpc_pkg && mv $mpc_dir mpc
	tar xf $gmp_pkg && mv $gmp_dir gmp
	tar xf $isl_pkg && mv $isl_dir isl
	cp -f config.* gcc-src
	cp -f config.guess gmp
	cp -f config.sub gmp/configfsf.sub
	for d in isl mpc mpfr; do cp -f config.* $d; done
	for d in gmp isl mpc mpfr; do autoreconf -if $d; done
	cp -r gmp isl mpc mpfr binutils-src
	mv gmp isl mpc mpfr gcc-src
	set +v
else
	echo ""
	verifysha256 $gcc_pkg $gcc_sum
	verifysha256 $binutils_pkg $binutils_sum
	verifysha256 $mpfr_pkg $mpfr_sum
	verifysha256 $mpc_pkg $mpc_sum
	verifysha256 $gmp_pkg $gmp_sum
	verifysha256 $isl_pkg $isl_sum
	echo ""
fi

