#!/bin/sh

set -e

verifysha256 () {
	sha256_2=$(sha256sum ${1} | head -c64)
	if [ $sha256_2 != ${2} ] ; then
		echo "${1}:"
		echo "SHA256 checksum is $sha256_2 but should be ${2}."
		echo "Delete '${1}' and try it again."
		exit 1
	else
		echo "${1}: checksum ok."
	fi
}

gcc_ver=5.2.0
gcc_dir=gcc-$gcc_ver
gcc_pkg=${gcc_dir}.tbz
gcc_url="http://ftp.gnu.org/gnu/gcc/gcc-$gcc_ver/${gcc_dir}.tar.bz2"
gcc_sum=5f835b04b5f7dd4f4d2dc96190ec1621b8d89f2dc6f638f9f8bc1b1014ba8cad

mpfr_dir=mpfr-3.1.3
mpc_dir=mpc-1.0.3
gmp_dir=gmp-6.1.0
mpfr_pkg=${mpfr_dir}.txz
mpc_pkg=${mpc_dir}.tgz
gmp_pkg=${gmp_dir}.txz
mpfr_url="http://www.mpfr.org/mpfr-current/${mpfr_dir}.tar.xz"
mpc_url="http://ftp.gnu.org/gnu/mpc/${mpc_dir}.tar.gz"
gmp_url="https://gmplib.org/download/gmp/${gmp_dir}.tar.xz"
mpfr_sum=6835a08bd992c8257641791e9a6a2b35b02336c8de26d0a8577953747e514a16
mpc_sum=617decc6ea09889fb08ede330917a00b16809b8db88c29c31bfbb49cbf88ecc3
gmp_sum=68dadacce515b0f8a54f510edf07c1b636492bcdb8e8d54c56eb216225d16989

isl_dir=isl-0.14.1
isl_pkg=${isl_dir}.txz
isl_url="http://isl.gforge.inria.fr/${isl_dir}.tar.xz"
isl_sum=8882c9e36549fc757efa267706a9af733bb8d7fe3905cbfde43e17a89eea4675

test -f $gcc_pkg || wget -O $gcc_pkg $gcc_url
test -f $mpfr_pkg || wget -O $mpfr_pkg $mpfr_url
test -f $mpc_pkg || wget -O $mpc_pkg $mpc_url
test -f $gmp_pkg || wget -O $gmp_pkg $gmp_url
test -f $isl_pkg || wget -O $isl_pkg $isl_url

if [ "x$1" = "x--extract" ]; then
	tar xf $gcc_pkg
	mv $gcc_dir gcc-src
	cd gcc-src

	tar xf ../$mpfr_pkg
	mv $mpfr_dir mpfr

	tar xf ../$mpc_pkg
	mv $mpc_dir mpc

	tar xf ../$gmp_pkg
	mv $gmp_dir gmp

	tar xf ../$isl_pkg
	mv $isl_dir isl
else
	echo ""
	verifysha256 $gcc_pkg $gcc_sum
	verifysha256 $mpfr_pkg $mpfr_sum
	verifysha256 $mpc_pkg $mpc_sum
	verifysha256 $gmp_pkg $gmp_sum
	verifysha256 $isl_pkg $isl_sum
	echo ""
fi

