include ../../mk/include.mk

ARCH           = amd64
deps           = wget
bin            = desura.tgz
srcfiles       = $(bin)
distcleanfiles = $(bin)

download:
	@ $(call download,$(bin),http://www.desura.com/desura-x86_64.tar.gz)

