debian/opensonic.desktop               /usr/share/applications
converted_icons/*                      /usr/share
/usr/share/games/opensonic/opensonic   /usr/lib/games/opensonic
/usr/share/games/opensonic/config
/usr/share/games/opensonic/images
/usr/share/games/opensonic/languages
/usr/share/games/opensonic/levels
/usr/share/games/opensonic/musics
/usr/share/games/opensonic/objects
/usr/share/games/opensonic/quests
/usr/share/games/opensonic/samples
/usr/share/games/opensonic/sprites
/usr/share/games/opensonic/themes
