#!/bin/sh

set -e

if [ "$1" = "remove" ] || [ "$1" = "deconfigure"] ; then
    /usr/lib/virtualbox/VBoxExtPackHelperApp uninstall \
        --base-dir /usr/lib/virtualbox/ExtensionPacks \
        --name 'Oracle VM VirtualBox Extension Pack'
fi

#DEBHELPER#

exit 0
