.TH GRPAR "1" "MAY 2015" "0.2"
.SH NAME
Grpar - extract Build engine group (.grp) files

.SH SYNOPSIS
.B grpar \fR[-h] [-V] [-t|-x] [-C path] [-v] -f grp_file [file_1] [file_2] [...]

.SH DESCRIPTION
Grpar is a tool to extract Build engine group (.grp) files.
See Ken Silverman's Build engine page (\fIhttp://advsys.net/ken/build.htm\fR) for more information.

.SH OPTIONS
.TP
\fB\-h\fR
this help
.TP
\fB\-V\fR
version
.TP
\fB\-t\fR
list files from group archive
.TP
\fB\-x\fR
extract files from group archive
.TP
\fB\-C\fR
specify destination directory
.TP
\fB\-v\fR
verbose mode
.TP
\fB\-f\fR
group archive

.SH COPYRIGHT
Copyright \(co 2010\-2014 Ganael LAPLANCHE <\fIganael.laplanche@martymac.org\fR>
