#!/bin/sh -e

gamedir=/usr/share/games/serena
confdir="$HOME/.config/serena"

if [ ! -d "$confdir" ] ; then
    mkdir -p "$confdir"
    cp $gamedir/config.lua "$confdir"
    ln -s $gamedir/resources "$confdir/resources"
    ln -s $gamedir/scripts "$confdir/scripts"
fi

cd "$confdir" && dagon "$@"
