include ../Makefile.inc

deps = git wget cmake libbz2-dev libfluidsynth-dev libgtk2.0-dev \
	libjpeg-dev libsdl1.2-dev zlib1g-dev
cleanfiles = fmodapi*linux zdoom debian/changelog *.tar.gz

download: clean
	./download.sh

