.TH "SERENA" "6" "November, 2014"
.SH NAME
.PP
Serena \- a point-and-click adventure game
.SH DESCRIPTION
.PP
How long has it been?
A man sits in a distant getaway cabin waiting for his wife Serena.
Where is she?
Things in the cabin evoke memories, and the husband comes to a disturbing realization...
.PP
This short point-and-click adventure is the result of a massive
collaborative effort between dozens of fans and designers of adventure games.
Rallying to support the venerable genre and its passionate community, these
developers have brought together a grim and highly detailed horror story in
what is the largest, possibly even the first, game project of its kind.
.PP
Talents include crew from renowned indie companies Senscape, CBE Software,
Infamous Quests, Digital Media Workshop, Guys from Andromeda, and many more.
.SH SUPPORT
.PP
Feel free to visit our forums to discuss the engine and request
technical support: http://www.senscape.net/forum
.SH AUTHORS
Copyright (c) 2014 Senscape s.r.l. All rights reserved.
.SH "SEE ALSO"
.BR dagon (6)
