include ../Makefile.inc

deps = git wget cmake libbz2-dev libfluidsynth-dev libglew-dev libgtk2.0-dev \
	libjpeg-dev libsdl1.2-dev zlib1g-dev
cleanfiles = fmodapi*linux gzdoom debian/changelog *.tar.gz


download: clean
	./download.sh

