.TH GCC\-STATIC-\WRAPPER 1 "September 2016" gcc\-static\-wrapper ""
.SH NAME
gcc\-static\-wrapper \- links GCC helper libraries statically

.SH DESCRIPTION
Links libgcc and/or libstdc++ always statically.
.PP
gcc\-static1: appends -static-libgcc to gcc commands
.br
g++\-static1: appends -static-libgcc to g++ commands
.br
g++\-static2: appends -static-libstdc++ to g++ commands
.br
g++\-static3: appends -static-libgcc -static-libstdc++ to g++ commands
