.TH GIANAS-RETURN 6 "MARCH 2016" 1.10
.SH NAME
gianas-return - unofficial sequel of "The Great Giana Sisters"

.SH SYNOPSIS
.B gianas-return
.I [options]

.SH DESCRIPTION

Evil Swampy and his followers have stolen the magic ruby, which made it once possible for Giana and Maria to return from their dream.
Many creatures are after this ruby, but does it really has power, or was it just a coincidence?
As this is not bad enough, Swampy fell in love at first sight with Giana's sister Maria and shamelessly kidnapped her.
She simply has been at the wrong place at the wrong time.
You will now have to take on the role of Giana and get back the magic ruby.
And most important of all, save your beloved sister Maria and get home save!
Good Luck!

.SH OPTIONS
.TP
.B \-w
window mode (not fullscreen)

.TP
.B \-fs
fullscreen (-x2 automatically added)

.TP
.B \-x2
zoom with no antialiasing

.TP
.B \-aa
zoom with antialiasing

.TP
.B \-b16
16 bits video mode

.TP
.B \-b24
24 bits video mode (maybe usefull if fade in/fade out looks crappy)

.TP
.B \-a11
audio playback at 11Khz

.TP
.B \-a22
audio playback at 22Khz

.TP
.B \-a44
audio playback at 44Khz

