#!/bin/sh

dir="$HOME/.ifme-bin"
url="https://sourceforge.net/projects/ifme/files/latest/download"

if [ "x$1" = "x-h" ] || [ "x$1" = "x--help" ]; then
  cat <<EOL
Usage: ifme-gui [OPTION]

Option:
  -h, --help                   show this help
  -r, --reinstall              re-install IFME

For more command line options use \`ifme' instead of \`ifme-gui'.

IFME home page: <https://x265.github.io/>
Report bugs to: <https://github.com/Anime4000/IFME/issues>
Facebook page : <https://fb.com/internetfriendlymediaencoder/>
EOL
  exit 0
fi
if [ "x$1" = "x-r" ] || [ "x$1" = "x--reset" ]; then
  rm -rf "$dir"
fi

if [ ! -d "$dir" ] || [ ! -x "$dir/ifme-xterm" ]; then
  rm -rf "$dir"
  mkdir -p "$dir"
  cd "$dir"
  ( wget -O ifme.txz $url 2>&1 | sed -u 's/^[a-zA-Z\-].*//; s/.* \{1,2\}\([0-9]\{1,3\}\)%.*/\1\n#Downloading... \1%/; s/^20[0-9][0-9].*/#Done./' | \
    zenity --progress \
           --title="Downloading IFME" \
           --text "Wait a few seconds until the donwload is finished ..." \
           --auto-close ) || exit 1
  tar xf ifme.txz
  if [ -d ifme6 ]; then
    mv ifme6 ifme_tmp
    mv ifme_tmp/* .
  fi
  rm -rf ifme_tmp ifme.txz
fi

if [ -x "$(which gnome-terminal 2>/dev/null)" ]; then
  cd "$dir" && ./ifme-gnome
else
  cd "$dir" && ./ifme-xterm
fi

