include ../../include.mk

deps = wget
srcfiles = opensnc-linux-0.1.4.tar.gz

download:
	wget -O opensnc-linux-0.1.4.tar.gz \
	   "http://downloads.sourceforge.net/project/opensnc/Open%20Sonic/0.1.4/opensnc-linux-0.1.4.tar.gz?ts=1420143879"
	tar xvf opensnc-linux-0.1.4.tar.gz

