.TH FREEDM 6 local
.SH NAME
freedm \- Open Source multiplayer-only Doom-clone
.SH SYNOPSIS
.B freedm
[\| engine arguments \|]
.SH DESCRIPTION
.B freedm
is a small shell script which invokes
.B boom
with the FreeDM resources supplied as an argument. This will start a
game of FreeDM. Please note that FreeDM is a multiplayer-only game.
.PP
.SH OPTIONS
All options are passed through to the
.B boom
program. Check to see what package is providing your
.B boom(6)
to see what options are available for your
.B boom
implementation.
.SH AUTHOR
This manpage was written by Jon Dowland <jmtd@debian.org> for
Debian GNU/Linux.
