.TH "THUNDERBIRD" "1" 
.SH "NAME" 
thunderbird \(em  thunderbird \- Mail User Agent (MUA) and newsgroup/RSS 
client for X11 derived from the Mozilla suite. 
.SH "SYNOPSIS" 
.PP 
\fBthunderbird\fR [\fB-P \fIprofile\fR\fP]  
.SH "DESCRIPTION" 
.PP 
Thunderbird provides IMAP/POP support, a built-in RSS reader, 
support for HTML mail, powerful quick search, saved search 
folders, advanced message filtering, junk mail controls, 
message grouping, labels, return receipts, smart address book 
LDAP address completion, import tools, and the ability to 
manage multiple identities in email and newsgroup accounts. 
Thunderbird provides enterprise and government grade security 
such as S/MIME, digital signing, message encryption, and support 
for certificates and security devices. 
.SH "OPTIONS" 
.IP "\fB-P \fIprofile\fR\fP         " 10 
If  no profile is given to the \-P option, the profile 
manager will pop-up. You will be allowed to create or 
select a profile.  Thunderbird then launches with the 
selected profile. 
.SH "SEE ALSO" 
.PP 
.nf 
The Thunderbird Homepage: 
http://www.mozilla.org/projects/thunderbird/ 
 
The Debian Thunderbird FAQ: 
http://www.jwsdot.com/debian/faq.html 
.fi 
.\" created by instant / docbook-to-man, Mon 30 Mar 2015, 22:41 
