.TH DESURA 6 "February 2015"

.SH NAME
desura \- digital software delivery system

.SH SYNOPSIS
.B desura \fR[options]

.SH OPTIONS
.B \-\-help
displays usage information
.TP
.B \-\-reset
deletes and re-downloads the local client files located at \fI$HOME/.local/share/desura\fR

.SH DESCRIPTION
Desura is a digital distribution platform developed by Bad Juju Games for the Microsoft Windows, Linux and OS X platforms.
The service distributes games and related media online, with a primary focus on small independent game
developers rather than larger companies.
Desura contains automated game updates, community features, and developer resources.
The client allows users to create and distribute game mods as well.

.SH "SEE ALSO"
The client files are located at \fI$HOME/.local/share/desura\fR

Configuration and other files used by the client are stored in \fI$HOME/.desura\fR

The Desura homepage: \fIhttp://www.desura.com\fR

