#!/bin/sh -e

config="$HOME/.config/duke3d-shareware"

test ! -d "$config" && mkdir -p "$config" || true
test ! -e "$config/DUKE3D.GRP" && \
  ln -s "/usr/share/games/duke3d-shareware/DUKE3D.GRP" "$config/DUKE3D.GRP" || true

cd "$config" && chocolate-duke3d "$@"

