#!/bin/sh -e

config="$HOME/.config/duke3d-shareware"

mkdir -p "$config"
cd "$config"

ln -fs "/usr/share/games/duke3d-shareware/DUKE3D.GRP"
ln -fs "/usr/lib/chocolate-duke3d"

./chocolate-duke3d "$@"

