.TH UTSERVER "1" "January 2015" "alpha v3.3" "User Commands"
.SH NAME
utserver \- µTorrent server
.SH SYNOPSIS
.B utserver
[OPTIONS]
.SH DESCRIPTION
.TP
.B \-settingspath \fIPATH
location of settings directory
.TP
.B \-logfile \fIPATH
location and name of log file
.TP
.B \-configfile \fIPATH
location and name of configuration file
.TP
.B \-pidfile \fIPATH
location and name of file to contain process ID
.TP
.B \-daemon
run process as a daemon
.TP
.B \-usage
print usage information
.SH HOMEPAGE
.I http://www.utorrent.com
