.TH STEAM 6 2012-06-19
.SH NAME
steam\-native \- a launcher for the Steam client from Valve Corporation
.SH SYNOPSIS
.B steam\-native
[
.BI - options
]
.SH DESCRIPTION
.B Steam
is a software distribution service focused on games, automatic updates, achievements, and social features for gamers.
.SH OPTIONS
This program currently has no documented commandline options.
.SH AUTHOR
The steam launcher script is written and maintained by Valve Corporation.
