#!/bin/sh

set -e

case "$1" in
configure)

    update-alternatives \
    --install \
        /usr/bin/flvextract flvextract \
        /usr/bin/FLVExtractCL 40 \
		--slave \
        /usr/share/man/man1/flvextract.1.gz flvextract.1.gz \
		    /usr/share/man/man1/FLVExtractCL.1.gz

    ;;
esac

#DEBHELPER#

exit 0
