.TH DAGON 6 "OCTOBER 2014"
.SH NAME
Dagon \- Adventure Game Engine

.SH DESCRIPTION
Dagon is a game engine especially tailored for adventure games and based on
open technologies.
Featuring a deceptively simple scripting language, blazing fast performance
and high portability supporting Windows, Linux, Mac OS X and iOS devices,
the project aims to become a reference of the genre.
.PP
The engine allows easy construction of node-based (so called "pseudo-3D")
games with a custom scripting language based on Lua, which is simple to learn
and features a reduced set of instructions.
The rotation in each node is panoramic (360 degrees) with added effects such
simulating the breathing of the protagonist.
Transitions between nodes are also sophisticated including head-bobbing,
thus giving the impression that the character is actually walking in real 3D.
.PP
Key among the features of Dagon are high performance and portability, which
means that games developed with the engine are expected to run smoothly even
on lower-end systems.
Windows, Mac OS X and major Linux distributions will be supported right out of
the box, with iOS support in the short term.
Support for building third person adventures is also planned.
.PP
The engine is completely based on open technologies, and therefore doesn't
require paying royalties or depends on prohibitive licenses or patents.

.SH EXAMPLES
You can find an example config file at
.I /usr/share/doc/dagon/examples/config.lua

.SH SEE ALSO
.I http://www.senscape.net/dagon/
.SH COPYRIGHT
Copyright \(co 2011-2014 Senscape s.r.l.
