--- a/Makefile
+++ b/Makefile
@@ -1,9 +1,17 @@
-CC?=gcc
-RM?=rm
-CFLAGS+=-O2 -Wall
+CC     := gcc
+CCLD   := gcc
+CFLAGS += -Wall -fno-strict-aliasing -I/usr/include/freebsd
 
-all: grpar.c
-	${CC} ${CFLAGS} grpar.c -o grpar
+bin = grpar
+
+
+all: $(bin)
+
+$(bin): $(bin).o
+	$(CCLD) $(LDFLAGS) -o $@ $^ -lbsd
+
+%.o: %.c
+	$(CC) -c $(CFLAGS) $(CPPFLAGS) -o $@ $^
 
 clean:
-	${RM} -f grpar
+	rm -f $(bin) $(bin).o
