ffmpeg/doc/doxy/html/*                  usr/share/doc/ffmpeg-doc/api
ffmpeg/doc/examples/*.c                 usr/share/doc/ffmpeg-doc/examples
ffmpeg/doc/examples/Makefile            usr/share/doc/ffmpeg-doc/examples
ffmpeg/doc/examples/README              usr/share/doc/ffmpeg-doc/examples
ffmpeg/doc/examples/pc-uninstalled      usr/share/doc/ffmpeg-doc/examples
ffmpeg/doc/*.html                       usr/share/doc/ffmpeg-doc/manual
ffmpeg/doc/*.css                        usr/share/doc/ffmpeg-doc/manual
ffmpeg/doc/APIchanges                   usr/share/doc/ffmpeg-doc/developer-info
ffmpeg/doc/*.txt                        usr/share/doc/ffmpeg-doc/developer-info
usr/share/man/man3
