.TH FFMPEG-X264_10BIT 1 "November 2015"
.SH NAME
ffmpeg-x264_10bit \- ffmpeg supporting 10 bit x264
.SH SYNOPSIS
.B ffmpeg-x264_10bit \fR[options]
.SH DESCRIPTION
.B ffmpeg-x264_10bit
is a shell script that runs ffmpeg with a pre-loaded version of libx264 that supports 10 bit output.
.SH OPTIONS
See \fBffmpeg --help\fR or \fBman ffmpeg\fR for more details.
.SH "SEE ALSO"
.BR ffmpeg (1),
.BR ld.so (8)
