include ../Makefile.inc

deps = wget
builddir = UnityEngine2deb-master
cleanfiles = master.tar.gz $(builddir)

build: build-default

download: clean
	wget "https://github.com/darealshinji/UnityEngine2deb/archive/master.tar.gz"
	tar xvf master.tar.gz

