--- a/OculusSDK/LibOVR/Makefile
+++ b/OculusSDK/LibOVR/Makefile
@@ -63,10 +63,10 @@
 
 DEBUG         = 0
 ifeq ($(DEBUG), 1)
-	CXXFLAGS      = -pipe -fPIC -DDEBUG -g
+	CXXBUILDFLAGS      = -Wall -pipe -O2 $(CXXFLAGS) $(CPPFLAGS) -DDEBUG -g
 	RELEASETYPE   = Debug
 else
-	CXXFLAGS      = -pipe -fPIC -O2
+	CXXBUILDFLAGS      = -Wall -pipe -O2 $(CXXFLAGS) $(CPPFLAGS)
 	RELEASETYPE   = Release
 endif
 
@@ -76,7 +76,7 @@
 3RDPARTYPATH  = ../3rdParty
 INCPATH       = -I. -I.. -I$(LIBOVRPATH)/Include -I$(LIBOVRPATH)/Src
 OBJPATH       = ./Obj/Linux/$(RELEASETYPE)/$(SYSARCH)
-CXXBUILD      = $(CXX) -c $(CXXFLAGS) $(INCPATH) -o $(OBJPATH)/
+CXXBUILD      = $(CXX) -c $(CXXBUILDFLAGS) $(INCPATH) -o $(OBJPATH)/
 
 ####### Files
 
