.TH HTERM 1 "0.8.1 beta" "December 2015"
.SH NAME
hterm \- Terminal program with in and output in ASCII, hex, binary and decimal
.SH SYNOPSIS
.B hterm
.SH OPTIONS
This program has no command line options.
.SH SEE ALSO
.I http://www.der-hammer.info/terminal/
.SH AUTHOR
Copyright \(co 2005\-2008 Tobias Hammer <hterm@der\-hammer.info>
