#!/bin/sh

set -e

if [ "$1" = "purge" ]; then
  rm -f /etc/apt/sources.list.d/google-chrome-stable.list
  rm -f /etc/apt/sources.list.d/google-chrome-stable.list.save

  APT_KEY="`which apt-key 2> /dev/null`"
  if [ -x "$APT_KEY" ]; then
    KEY="$(apt-key list | grep -B 1 -e 'Google, Inc. Linux Package Signing Key' | head -n1 | cut -d '/' -f2 | cut -d ' ' -f1)"
    if [ x"$KEY" != x ]; then
      "$APT_KEY" del "$KEY" >/dev/null 2>&1
    fi
  fi
fi

#DEBHELPER#

