#!/bin/sh

set -e

if [ "$1" = "remove" ]; then
   update-alternatives --remove x-www-browser /usr/bin/google-chrome-stable
   update-alternatives --remove gnome-www-browser /usr/bin/google-chrome-stable
   update-alternatives --remove google-chrome /usr/bin/google-chrome-stable
fi

#DEBHELPER#

