include ../../mk/include.mk

deps     = wget
builddir = UnityEngine2deb-master

download:
	@ $(call download,u2deb.tar.gz,https://github.com/darealshinji/UnityEngine2deb/archive/master.tar.gz)
	tar xvf u2deb.tar.gz

