#!/bin/sh

# I, djcj <djcj@gmx.de>, hereby release this code to the Public Domain.
# No license required for any purpose; the work is not subject to copyright in any jurisdiction.

set -e

verifysha256 () {
	sha256_2=$(sha256sum ${1} | head -c64)
	if [ $sha256_2 != ${2} ] ; then
		echo "${1}:"
		echo "SHA256 checksum is $sha256_2 but should be ${2}."
		echo "Delete '${1}' and try it again."
		exit 1
	else
		echo "${1}: checksum ok."
	fi
}

gcc_ver=8.1.0
gcc_dir=gcc-$gcc_ver
gcc_pkg=${gcc_dir}.txz
gcc_url="https://ftp.gnu.org/gnu/gcc/gcc-$gcc_ver/${gcc_dir}.tar.xz"
gcc_sum=1d1866f992626e61349a1ccd0b8d5253816222cdc13390dcfaa74b093aa2b153

binutils_ver=2.30
binutils_dir=binutils-$binutils_ver
binutils_pkg=${binutils_dir}.txz
binutils_url="https://ftp.gnu.org/gnu/binutils/${binutils_dir}.tar.xz"
binutils_sum=6e46b8aeae2f727a36f0bd9505e405768a72218f1796f0d09757d45209871ae6

mpfr_dir=mpfr-4.0.1
mpc_dir=mpc-1.1.0
gmp_dir=gmp-6.1.2
isl_dir=isl-0.19

mpfr_pkg=${mpfr_dir}.txz
mpc_pkg=${mpc_dir}.tgz
gmp_pkg=${gmp_dir}.txz
isl_pkg=${isl_dir}.txz

mpfr_url="http://www.mpfr.org/${mpfr_dir}/${mpfr_dir}.tar.xz"
mpc_url="https://ftp.gnu.org/gnu/mpc/${mpc_dir}.tar.gz"
gmp_url="https://gmplib.org/download/gmp/${gmp_dir}.tar.xz"
isl_url="http://isl.gforge.inria.fr/${isl_dir}.tar.xz"

mpfr_sum=67874a60826303ee2fb6affc6dc0ddd3e749e9bfcb4c8655e3953d0458a6e16e
mpc_sum=6985c538143c1208dcb1ac42cedad6ff52e267b47e5f970183a3e75125b43c2e
gmp_sum=87b565e89a9a684fe4ebeeddb8399dce2599f9c9049854ca8c0dfbdea0e21912
isl_sum=6d6c1aa00e2a6dfc509fa46d9a9dbe93af0c451e196a670577a148feecf6b8a5

test -f $gcc_pkg || wget -O $gcc_pkg $gcc_url
test -f $binutils_pkg || wget -O $binutils_pkg $binutils_url
test -f $mpfr_pkg || wget -O $mpfr_pkg $mpfr_url
test -f $mpc_pkg || wget -O $mpc_pkg $mpc_url
test -f $gmp_pkg || wget -O $gmp_pkg $gmp_url
test -f $isl_pkg || wget -O $isl_pkg $isl_url

if [ "x$1" = "x--extract" ]; then
	set -v
	tar xf $binutils_pkg && mv $binutils_dir binutils-src
	tar xf $gcc_pkg && mv $gcc_dir gcc-src
	tar xf $mpfr_pkg && mv $mpfr_dir mpfr
	tar xf $mpc_pkg && mv $mpc_dir mpc
	tar xf $gmp_pkg && mv $gmp_dir gmp
	tar xf $isl_pkg && mv $isl_dir isl
	cp -f config.* gcc-src
	cp -f config.guess gmp
	cp -f config.sub gmp/configfsf.sub
	for d in isl mpc mpfr; do cp -f config.* $d; done
	for d in gmp isl mpc mpfr; do autoreconf -if $d; done
	cp -r gmp isl mpc mpfr binutils-src
	mv gmp isl mpc mpfr gcc-src
	set +v
else
	echo ""
	verifysha256 $gcc_pkg $gcc_sum
	verifysha256 $binutils_pkg $binutils_sum
	verifysha256 $mpfr_pkg $mpfr_sum
	verifysha256 $mpc_pkg $mpc_sum
	verifysha256 $gmp_pkg $gmp_sum
	verifysha256 $isl_pkg $isl_sum
	echo ""
fi

