.TH IFME 1 "April 2016"
.SH NAME
IFME\-GUI \- Internet Friendly Media Encoder (GUI)
.SH SYNOPSIS
.B ifme\-gui
.SH DESCRIPTION
.B ifme\-gui
will launch the graphical user interface.
.PP
For more command line options use
.BR ifme (1).
.SH OPTIONS
.TP
.B \-h\fR, \fB\-\-help
show help
.TP
.B \-r\fR, \fB\-\-reinstall
re-install IFME
.SH "SEE ALSO"
Configuration files are located in \fI~/.local/share/Anime4000/\fR
.br
IFME's executable binary files are located in \fI~/.ifme\-bin/\fR
.PP
Official homepage:
.I https://x265.github.io/
.PP
Source code repository:
.I https://github.com/Anime4000/IFME
