.TH IFME 1 "April 2016"
.SH NAME
IFME \- Internet Friendly Media Encoder
.SH SYNOPSIS
.B ifme \fR[OPTION...] -i INPUT
.SH DESCRIPTION
.B IFME
is an easy to use GUI that helps you to encode your HEVC videos.
.SH OPTIONS
.TP
.B \-h\fR, \fB\-\-help
show help
.TP
.B \-r\fR, \fB\-\-reset
reset IFME configuration
.TP
.B \-g\fR, \fB\-\-gui
open IFME GUI
.TP
.B \-c\fR, \fB\-\-cli
open IFME CLI (impiles -g)
.TP
.B \-i\fR, \fB\-\-input \fIfile.xml
load IFME queue file via CLI
.TP
.B \-s\fR, \fB\-\-offline
skip all update checking (faster loading)
.TP
.B \-f
start encoding immediately (skip confirmation)
.SH "SEE ALSO"
Configuration files are located in \fI~/.local/share/Anime4000/\fR
.br
IFME's executable binary files are located in \fI~/.ifme\-bin/\fR
.PP
Official homepage:
.I https://x265.github.io/
.PP
Source code repository:
.I https://github.com/Anime4000/IFME
