compiled/dist/xulrunner/res      /usr/share/nightingale/xulrunner
compiled/dist/xulrunner/chrome   /usr/share/nightingale/xulrunner
compiled/dist/chrome             /usr/share/nightingale
addons/*.xpi                     /usr/lib/nightingale/addons
minimizetotray.xpi               /usr/lib/nightingale/addons
compiled/xpi-stage/shoutcast-radio/shoutcast-radio*.xpi   /usr/lib/nightingale/addons
libjpeg.so.8                     /usr/lib/nightingale/xulrunner
