.TH FREEDOOM1 6 local
.SH NAME
freedoom1 \- Open Source Doom-clone - Phase 1 maps
.SH SYNOPSIS
.B freedoom1
[\| engine arguments \|]
.SH DESCRIPTION
.B freedoom1
is a small shell script which invokes
.B boom
with the FreeDoom resources supplied as an argument. This will start a
game of FreeDoom.
.PP
.SH OPTIONS
All options are passed through to the
.B boom
program. Check to see what package is providing your
.B boom(6)
to see what options are available for your
.B boom
implementation.
.SH AUTHOR
This manpage was written by Jon Dowland <jmtd@debian.org> for
Debian GNU/Linux.
