.TH ANIMECHECKER "1" "July 2017" "v0.9.6.1"

.SH NAME
animechecker \- graphical CRC32 checksum calculator

.SH DESCRIPTION
\fBAnime Checker\fR is a tool that calculates the CRC32 of your files.
The CRC is a 8 hexadecimal characters that most fansubbers include at the end
of their releases filename (like my_video_[A3B6DF52].avi).
To check the file integrity, Anime Checker will compute the CRC value of the
file and compare it with the given CRC value.
If it's the same, there are nothing wrong with the file.
If it's not the same, the file is probably corrupted or incomplete.

.SH OPTIONS
There are no command line options available.
Use
.BR acc (1)
instead.

