.TH RBDOOM3BFG 6 "January 2015"
.SH NAME
rbdoom3bfg \- Doom 3 BFG Edition
.SH SYNOPSIS
.B rbdoom3bfg

.SH DESCRIPTION
To play the game, you need the game data from a legal copy of the
game, which unfortunately requires Steam for Windows \- Steam for
Linux won't do, because (at least currently) the Doom 3 BFG game
is only installable on Steam for Windows.
Even the DVD version of Doom 3 BFG only contains encrytped data
that is decoded by Steam on install.

Fortunately, you can run Steam in Wine to install Doom3 BFG and
afterwards copy the game data somewhere else to use it with native
executables.
Winetricks (\fIhttp://winetricks.org/\fR) makes installing Windows
Steam on Linux really easy.

1. Install Winetricks (\fBsudo apt\-get install winetricks\fR) and run
.B winetricks steam

2. Install Doom 3 BFG in Steam (Windows version), make sure it's
getting updated/patched.

3. Copy the game\-data's base dir in
.I ~/.steam/steamapps/common/DOOM 3 BFG Edition/base/
to \fI/usr/share/games/doom3bfg

.SH "SEE ALSO"
.I https://github.com/RobertBeckebans/RBDOOM-3-BFG
