#!/bin/sh
set -e

if [ "$1" = "configure" ]; then
    ldconfig
fi

for d in profiles gcroots;
do
    DIR=/nix/var/nix/$d/per-user
    if [ ! -d $DIR ]; then
        mkdir -p $DIR
        chmod 1777 $DIR
    fi
done

STORE_DIR=/nix/store
if [ ! -d $STORE_DIR ]; then
    mkdir -p $STORE_DIR
    chmod 1775 $STORE_DIR
fi

LISP_DIR=/nix/share/emacs/site-lisp
if [ ! -f $LISP_DIR/nix-mode.el ]; then
    if [ ! -d $LISP_DIR ]; then
        mkdir -p $LISP_DIR
    fi
    cp /usr/share/emacs24/site-lisp/nix-mode.el $LISP_DIR
fi

#DEBHELPER#

exit 0
