#!/bin/sh -e

case "$1" in
    configure)
    update-alternatives --install /usr/lib/divx/libdivx.so libdivx \
        /usr/lib/libdivx.so 100
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
	exit 0
    ;;

    *)
	echo "postinst called with unknown argument \`$1'" >&2
	exit 0
    ;;
esac

exit 0

