.\" http://www.piratehearts.com/blog/2012/10/28/you-have-to-mod-the-game/
.TH THEGAME-EGA 6 "MAY 2014" "2012-10-28"
.SH NAME
thegame-ega - EGA tileset for "You Have to Win the Game"
.SH SYNOPSIS
.B thegame-ega
.br
.B yhtwtg-ega
.SH DESCRIPTION
Experience the game in stunning \fB6-bit colors!!
.SH SEE ALSO
.BR thegame(6)
.br
.I http://www.piratehearts.com
.SH AUTHOR
This manual page was written by djcj <djcj@gmx.de>.
.PP
\fBYou Have to Win the Game\fP and the EGA mod were
made by J. Kyle Pittman <jpittman@gmail.com>.
