.TH THEGAME 6 "MAY 2014" "1.01.0405"
.SH NAME
thegame - You Have to Win the Game
.SH SYNOPSIS
.B thegame
.br
.B yhtwtg
.SH DESCRIPTION
\fBYou Have to Win the Game\fP is an exploration platformer
with a retro 1980s PC aesthetic.
.PP
It features two difficulty modes, a developer console,
optional CRT simulation and USB gamepad support.
.SH OPTIONS
All options are made within the game's menu settings.
The configuration and saved games are stored in
"/.local/share/Minor Key Games/You Have to Win the Game".
Custom made textures are stored in the configuration's subfolder "Mods".
.SH SEE ALSO
.BR thegame-ega(6)
.br
.I http://www.piratehearts.com
.SH AUTHOR
This manual page was written by djcj <djcj@gmx.de>.
.PP
\fBYou Have to Win the Game\fP was made
by J. Kyle Pittman <jpittman@gmail.com>.
