#!/bin/sh -e

GAMEDIR=/usr/share/games/asylum-teaser
CONFDIR="$HOME/.asylum-teaser"

if [ ! -d "$CONFDIR" ] ; then
    mkdir -p "$CONFDIR"
    cp $GAMEDIR/config.lua "$CONFDIR"
    ln -s $GAMEDIR/resources "$CONFDIR/resources"
    ln -s $GAMEDIR/scripts "$CONFDIR/scripts"
fi

cd "$CONFDIR" && dagon "$@"
