.TH "ASYLUM\-TEASER" "6" "November, 2014" "" ""
.SH NAME
.PP
Asylum \- The Interactive Teaser
.SH DESCRIPTION
.PP
In \f[I]Asylum\f[], you set out on a chilling journey through the
intricate floors of the Hanwell Mental Institute, which has seen
unimaginable atrocities in the past.
Decay surrounds you; dread awaits you around every corner.
As you traverse the endless corridors of the asylum, a disconcerting
feeling of imprisonment creeps up on you...
.PP
\f[I]Asylum\f[]\ is the upcoming psychological horror adventure game by
Senscape and inspired by H.P.
Lovecraft, set in a massive mental institute that is far past its prime.
Over four years in production, it aims to marry cutting edge visuals
with thrilling storytelling to give players the ultimate experience of
fear.
.SS The Teaser
.PP
This is a very short demo not featuring actual content from the game.
It\[aq]s intended as a first glimpse into the sort of atmosphere and
gameplay that can be found in \f[I]Asylum\f[].
We\[aq]re making its source code available for fun and educational
purposes.
The engine behind this project \- Dagon \- has also been open sourced
here: https://github.com/Senscape/Dagon
.SH SUPPORT
.PP
Feel free to visit our forums to discuss the engine and request
technical support: http://www.senscape.net/forum
.SH AUTHORS
Copyright (c) 2012 Senscape s.r.l. All rights reserved.
